name: Testing Master
on: 
  push:
    branches: 
      - main
      - dev
  pull_request:
    branches:
     - main 
     - dev
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Update Ubuntu
      run: sudo apt update
    - name: Install Dependencies
      run: sudo apt install python3 python3-venv
    - name: Create Venv
      run: python3 -m venv venv && source venv/bin/activate 
    - name: install setuptools
      run: source venv/bin/activate && pip3 install setuptools
    - name: other packages
      run: source venv/bin/activate && pip3 install -r requirements.txt && pip3 install pylint
    - name: Install SCALE-Sim
      run: source venv/bin/activate && python3 setup.py install
    - name: Install tkinter
      run: sudo apt-get install python3-tk
    - name: Linting
      run: source venv/bin/activate && python3 -m pylint --fail-under=7.5 scalesim/
      continue-on-error: true
      # To test the default SCALE-Sim run
    - name: Run default SCALE-Sim configuration
      run: |
         source venv/bin/activate && cd scalesim && python3 scale.py
         deactivate
      continue-on-error: true
      # To test the functionality of weight stationary dataflow in estimate bandwidth mode
    - name: Run general script file for estimate bandwidth mode and ws dataflow
      run: |
         source venv/bin/activate
         chmod +x ./test/general/scripts/diff_calc.sh
         ./test/general/scripts/diff_calc.sh
      shell: bash
      continue-on-error: true
      # To test the functionality of weight stationary dataflow in user bandwidth mode
    - name: Run general script file for user bandwidth mode and ws dataflow
      run: |
         source venv/bin/activate
         chmod +x ./test/general/scripts/diff_user_ws.sh
         ./test/general/scripts/diff_user_ws.sh
      shell: bash
      continue-on-error: true
      # To test the functionality of input stationary dataflow in user bandwidth mode
    - name: Run general script file for user bandwidth mode and is dataflow
      run: |
         source venv/bin/activate
         chmod +x ./test/general/scripts/diff_user_is.sh
         ./test/general/scripts/diff_user_is.sh
      shell: bash
      continue-on-error: true
      # To test the functionality of output stationary dataflow in user bandwidth mode
    - name: Run general script file for user bandwidth mode and os dataflow
      run: |
         source venv/bin/activate
         chmod +x ./test/general/scripts/diff_user_os.sh
         ./test/general/scripts/diff_user_os.sh
      shell: bash
      continue-on-error: true
      # To test sparsity functionality
    - name: Run sparsity script file
      run: |
         source venv/bin/activate
         chmod +x ./test/sparsity/scripts/function_test.sh
         ./test/sparsity/scripts/function_test.sh
      shell: bash
